-- Idempotent RLS policy reset for all tables.
-- Run this after any schema change or DB reset to restore row-level security.
-- Generated by scripts/apply-rls.js during `npm run build`.

-- transactions
ALTER TABLE "transactions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "transactions";
CREATE POLICY "allow_all" ON "transactions" FOR ALL USING (true) WITH CHECK (true);

-- platforms
ALTER TABLE "platforms" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "platforms";
CREATE POLICY "allow_all" ON "platforms" FOR ALL USING (true) WITH CHECK (true);

-- platform_orders
ALTER TABLE "platform_orders" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "platform_orders";
CREATE POLICY "allow_all" ON "platform_orders" FOR ALL USING (true) WITH CHECK (true);

-- platform_order_items
ALTER TABLE "platform_order_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "platform_order_items";
CREATE POLICY "allow_all" ON "platform_order_items" FOR ALL USING (true) WITH CHECK (true);

-- products
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "products";
CREATE POLICY "allow_all" ON "products" FOR ALL USING (true) WITH CHECK (true);

-- flavors
ALTER TABLE "flavors" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "flavors";
CREATE POLICY "allow_all" ON "flavors" FOR ALL USING (true) WITH CHECK (true);

-- inventory
ALTER TABLE "inventory" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "inventory";
CREATE POLICY "allow_all" ON "inventory" FOR ALL USING (true) WITH CHECK (true);

-- inventory_movements
ALTER TABLE "inventory_movements" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "inventory_movements";
CREATE POLICY "allow_all" ON "inventory_movements" FOR ALL USING (true) WITH CHECK (true);

-- padel_venues
ALTER TABLE "padel_venues" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "padel_venues";
CREATE POLICY "allow_all" ON "padel_venues" FOR ALL USING (true) WITH CHECK (true);

-- padel_deliveries
ALTER TABLE "padel_deliveries" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "padel_deliveries";
CREATE POLICY "allow_all" ON "padel_deliveries" FOR ALL USING (true) WITH CHECK (true);

-- padel_delivery_items
ALTER TABLE "padel_delivery_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "padel_delivery_items";
CREATE POLICY "allow_all" ON "padel_delivery_items" FOR ALL USING (true) WITH CHECK (true);

-- padel_sales
ALTER TABLE "padel_sales" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "padel_sales";
CREATE POLICY "allow_all" ON "padel_sales" FOR ALL USING (true) WITH CHECK (true);

-- rnd_projects
ALTER TABLE "rnd_projects" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "rnd_projects";
CREATE POLICY "allow_all" ON "rnd_projects" FOR ALL USING (true) WITH CHECK (true);

-- rnd_expenses
ALTER TABLE "rnd_expenses" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "rnd_expenses";
CREATE POLICY "allow_all" ON "rnd_expenses" FOR ALL USING (true) WITH CHECK (true);

-- supplies
ALTER TABLE "supplies" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "supplies";
CREATE POLICY "allow_all" ON "supplies" FOR ALL USING (true) WITH CHECK (true);

-- supply_purchases
ALTER TABLE "supply_purchases" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "supply_purchases";
CREATE POLICY "allow_all" ON "supply_purchases" FOR ALL USING (true) WITH CHECK (true);

-- financial_projections
ALTER TABLE "financial_projections" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "financial_projections";
CREATE POLICY "allow_all" ON "financial_projections" FOR ALL USING (true) WITH CHECK (true);

-- import_logs
ALTER TABLE "import_logs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "import_logs";
CREATE POLICY "allow_all" ON "import_logs" FOR ALL USING (true) WITH CHECK (true);

-- marketing_giveaways
ALTER TABLE "marketing_giveaways" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "marketing_giveaways";
CREATE POLICY "allow_all" ON "marketing_giveaways" FOR ALL USING (true) WITH CHECK (true);

-- marketing_giveaway_items
ALTER TABLE "marketing_giveaway_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "marketing_giveaway_items";
CREATE POLICY "allow_all" ON "marketing_giveaway_items" FOR ALL USING (true) WITH CHECK (true);

-- physical_assets
ALTER TABLE "physical_assets" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "physical_assets";
CREATE POLICY "allow_all" ON "physical_assets" FOR ALL USING (true) WITH CHECK (true);

-- rnd_inventory_usages
ALTER TABLE "rnd_inventory_usages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "rnd_inventory_usages";
CREATE POLICY "allow_all" ON "rnd_inventory_usages" FOR ALL USING (true) WITH CHECK (true);

-- product_variants
ALTER TABLE "product_variants" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "product_variants";
CREATE POLICY "allow_all" ON "product_variants" FOR ALL USING (true) WITH CHECK (true);

-- product_variant_ingredients
ALTER TABLE "product_variant_ingredients" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "product_variant_ingredients";
CREATE POLICY "allow_all" ON "product_variant_ingredients" FOR ALL USING (true) WITH CHECK (true);

-- ingredient_price_history
ALTER TABLE "ingredient_price_history" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "ingredient_price_history";
CREATE POLICY "allow_all" ON "ingredient_price_history" FOR ALL USING (true) WITH CHECK (true);

-- customer_orders
ALTER TABLE "customer_orders" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "customer_orders";
CREATE POLICY "allow_all" ON "customer_orders" FOR ALL USING (true) WITH CHECK (true);

-- customer_order_items
ALTER TABLE "customer_order_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON "customer_order_items";
CREATE POLICY "allow_all" ON "customer_order_items" FOR ALL USING (true) WITH CHECK (true);
